### ISSUE TITLE
CDK8S Strips out enums with with colons in them 

### ISSUE THREAD

**Issue by KamalAman** [cdk8s-team/cdk8s-cli#1072]
### Description of the bug:

When importing this CRD from Terraform [app.terraform.io_workspaces](https://github.com/hashicorp/terraform-cloud-operator/blob/main/charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml) CDK8S generates the following invalid Syntax for the NotificationTriggers

![image](https://github.com/cdk8s-team/cdk8s-cli/assets/2692357/fa722eef-e1c5-40ce-9d18-e9fb3ba542b3)

These enums are being stripped out because they contain a colon in them: 
![image](https://github.com/cdk8s-team/cdk8s-cli/assets/2692357/7f70fb5d-50c4-44c1-a6bb-b4e072fa2c17)

First: enums with colons in them should be supported
Second: CDK8S should not be generating invalid Typescript by creating multiple entries for STRIPPED_BY_CDK8S

This issue can be referenced in a few other spots: 
[#229](https://github.com/cdk8s-team/cdk8s-cli/issues/229)
[#267](https://github.com/cdk8s-team/cdk8s-cli/issues/267)
[#578](https://github.com/cdk8s-team/cdk8s-cli/issues/578)

There was one bug fixed here: https://github.com/cdk8s-team/cdk8s-cli/pull/196 for spaces, but none the less it stil persists for other characters. 

### Reproduction Steps:

Import the terraform workspace crd and generate

### Error Log:

Duplicate identifier 'STRIPPED_BY_CDK8S'

### Environment:

  - **Framework Version**:  2.2.90
  - **OS**: OSX

### Other:

---

This is :bug: Bug Report

**Comment by rassie** [comment]
Not only colons, it seems. My use-case is at https://github.com/redhat-cop/patch-operator, which just defines allowed MIME types

![image](https://github.com/cdk8s-team/cdk8s-cli/assets/23448/5cb3c7ac-571f-49f3-afd6-d95c6e3fa77e)

resulting in 

![image](https://github.com/cdk8s-team/cdk8s-cli/assets/23448/3be7e504-ec18-41ba-b08d-604fcbd4005a)
