### ISSUE TITLE
Control over synthesize console output

### ISSUE THREAD

**Issue by vbatoufflet** [cdk8s-team/cdk8s-cli#13]
After each synthesize run, `cdk8s synth` outputs a list of YAML files it has found in the output directory or the "No manifests synthesized" message if none.

For the purpose of example, let's say our CDK wants to generate a custom file system hierarchy:

```
cluster/
├── namespaces
│   └── demo
│       ├── deployments
│       │   └── test.k8s.yaml
│       └── service-accounts
│           └── test.k8s.yaml
└── roles
    └── custom-role.k8s.yaml
```

The console ends up with the "No manifests synthesized" message as only files directly under the output directory are checked for: https://github.com/cdk8s-team/cdk8s-cli/blob/main/src/util.ts#L50-L60

I can think of few possible changes to address this:
* walk the file system recursively to look for YAML files (which might be far from ideal, e.g. possible amount of sub-folders)
* keep the current `fs.readDir` call as is and introduce a `--silent` (or `--quiet`) flag to skip this kind of output

The second solution might be implemented by moving the code block mentioned before here https://github.com/cdk8s-team/cdk8s-cli/blob/main/src/cli/cmds/synth.ts#L42 and rely on the newly implemented flag.

I'll gladly provide you with a PR given that my solution suits to you. Please let me know what do you think about this.

**Comment by vbatoufflet** [comment]
What do you think about this? Could such a PR be of interest?

**Comment by Chriscbr** [comment]
This sounds reasonable - go for it! I think listing all generated YAML files in the output directory (regardless of whether they are nested within folders) seems like the most natural behavior to me. [glob](https://www.npmjs.com/package/glob) can be used to do the work of traversing the file system tree.
