### ISSUE TITLE
What's happening with CDK8S version 1.0.73

### ISSUE THREAD

**Issue by akefirad** [cdk8s-team/cdk8s-cli#171]
### Description of the bug (should be moved to cli repo):

I just upgraded to version 1.0.73 and my pipeline is totally broken with huge amount of logs starting with:
```
LIBERTY LIBERTY LIBERTY
LIBERTY LIBERTY LIBERTY
LIBERTY LIBERTY LIBERTY
```
And the source code is like (american.js):
```
module.exports = function americanFlag () {
  console.log('LIBERTY LIBERTY LIBERTY'.yellow);
  console.log('LIBERTY LIBERTY LIBERTY'.america);
  console.log('LIBERTY LIBERTY LIBERTY'.yellow);
  let flag = "\
  \
                                 !\
             H|H|H|H|H           H__________________________________\
             H|§|§|§|H           H|* * * * * *|---------------------|\
             H|§|∞|§|H           H| * * * * * |---------------------|\
             H|§|§|§|H           H|* * * * * *|---------------------|\
             H|H|H|H|H           H| * * * * * |---------------------|\
             H|H|H|H|H           H|---------------------------------|\
          ===============        H|---------------------------------|\
            /| _   _ |\          H|---------------------------------|\
            (| O   O |)          H|---------------------------------|\
            /|   U   |\          H-----------------------------------\
             |  \=/  |           H\
              \_..._/            H\
              _|\I/|_            H\
      _______/\| H |/\_______    H\
     /       \ \   / /       \   H\
    |         \ | | /         |  H\
    |          ||o||          |  H\
    |    |     ||o||     |    |  H\
    |    |     ||o||     |    |  H   Carl Pilcher\
  ";

  console.log(flag);

}
```
Update: it could be due to some other dependency upgrade, checking.
OK, it's about this https://news.ycombinator.com/item?id=25032105
Solution: pin colors version to 1.4.0.

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@akefirad Thanks for this. Fix coming up.

**Comment by iliapolo** [comment]
> Still facing issue after pinning colors npm version to 1.4.0. Any idea how to resolve ?

Pinning to `1.4.0` should resolve this. Depending on your project setup it can be a little tricky to accomplish though. Can you share exactly how you tried it?

**Comment by harkeet** [comment]
> Pinning to 1.4.0 should resolve this. Depending on your project setup it can be a little tricky to accomplish though. Can you share exactly how you tried it?

@iliapolo Thanks for the quick fix. Version upgrade to 1.0.74 solved the issue.
