### ISSUE TITLE
`cdk8s import` missing k8s 1.19 API spec on cdk8s-cli@1.0.92

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [cdk8s-team/cdk8s-cli#192]
# Description

Looks like we've run into this issue before here: https://github.com/cdk8s-team/cdk8s-cli/issues/23

I don't really want to downgrade all the way to v1.0.0-beta.27 from v1.0.92 in order to work around this issue. Is there a new recommended workaround for this?

# How to reproduce
using `cdk8s-cli@1.0.92`, run the following command in a TypeScript cdk8s app:

```sh
cdk8s import k8s@1.19
```

# Observed behavior:

The following URLs:
- https://raw.githubusercontent.com/awslabs/cdk8s/master/kubernetes-schemas/v1.19.8/_definitions.json 
- https://raw.githubusercontent.com/awslabs/cdk8s/master/kubernetes-schemas/v1.19/_definitions.json 

Both respond with a `404`.

![image](https://user-images.githubusercontent.com/20074921/152896320-3a063a4a-362c-4e70-884b-49529fd4aaf6.png)

![image](https://user-images.githubusercontent.com/20074921/152896702-2f7c4236-aaf7-41c3-94e9-5f4b77fe7442.png)

# Expected Behavior

k8s 1.19 is available to download via `cdk8s import k8s@1.19`, [as the `cdk8s` docs imply here](https://cdk8s.io/docs/latest/cli/import/#api-object-versions):
![image](https://user-images.githubusercontent.com/20074921/152896534-71479d8c-8968-4bd3-8649-c8c7a4c5581c.png)

**Comment by IsaacLeeWebDev** [comment]
Looks like running this works!

```sh
cdk8s import k8s@1.19.0
```

This can probably be closed with a little bit better error-logging and clearer docs that spell out that 

1. You can only pick from the versions listed here: https://github.com/cdk8s-team/cdk8s/tree/master/kubernetes-schemas
2. The version needs to include all three numbers.

**Comment by Chriscbr** [comment]
Oof - that sounds like it was frustrating to debug. 😕

I agree, we should add some validation here to avoid confusion in the future (and update any docs as needed). Thanks for reporting this.
