### ISSUE TITLE
Import from crds.dev assumes version tag starts with "v"

### ISSUE THREAD

**Issue by msessa** [cdk8s-team/cdk8s-cli#193]
The import from crds.dev assumes that each version tag begins with "v" (eg `v1.0.0`)

This is not always the case. [Example](https://doc.crds.dev/github.com/external-secrets/kubernetes-external-secrets)

Offending line:
https://github.com/cdk8s-team/cdk8s-cli/blob/01d73e5453701a44ae3341ebf81101c72d9451e6/src/import/crds-dev.ts#L36

**Comment by Chriscbr** [comment]
I see - it looks like version tags starting with "v" is a convention but isn't necessarily required. But I think changing this to require specifying "v" would probably be a breaking change, so I'm not quite sure if that kind of fix would be worthwhile.

Does the import work if you provide the entire URL (`https://doc.crds.dev/raw/github.com/external-secrets/kubernetes-external-secrets@8.5.2`)?

**Comment by msessa** [comment]
Hi @Chriscbr,

Good call. Using the URL directly works as intended so I'm gonna close this.
I agree that a breaking change isn't worth it since there's a viable workaround.

Thanks for your help.
