### ISSUE TITLE
Permission Error Thrown While Running CDK8s within Lambda Function that writes a File to TMP directory

### ISSUE THREAD

**Issue by drosket** [cdk8s-team/cdk8s-cli#24]
### Description of the bug:
CDK8s running in Lambda fails when CDK8s attempts to create a file in /tmp.   The failure appears to occur because it first attempts to write to the home directory before piping it to stdout where it is redirected to /tmp.  

The same code works in CDK but not in CDK8s.  
It appears that CDK8s is attempting to write to the users/home directory first before piping it to /tmp.   
Suspected source code information provided in "Other".  

### Reproduction Steps:
Running CDK8s in any Lambda function that attempts to write a file (ie: JSON) to /tmp directory.  

### Error Log:
"permission denied".   

### Environment:
AWS Lambda function (with CDK8s).  

### Other:
[https://github.com/cdk8s-team/cdk8s/commit/bbf116b93d9a14c24094aa51ec3a383489341190 ](https://github.com/cdk8s-team/cdk8s/commit/bbf116b93d9a14c24094aa51ec3a383489341190)
[https://github.com/cdk8s-team/cdk8s/blob/bbf116b93d9a14c24094aa51ec3a383489341190/packages/cdk8s-cli/src/cli/cmds/synth.ts](https://github.com/cdk8s-team/cdk8s/blob/bbf116b93d9a14c24094aa51ec3a383489341190/packages/cdk8s-cli/src/cli/cmds/synth.ts)

Suspect Line 38:      fs.createReadStream(path.join(tempDir, f)).pipe(process.stdout);

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
@drosket I see you mention `fs.createReadStream` could be the culprit of the permission error, but this only runs if the `--stdout` flag is passed - were you using this flag?

As a workaround, it's possible you could write the files to a directory that is writeable in the Lambda by using the `--outdir` flag instead, and then run e.g. `cat /path/to/outdir` to pass that information to STDOUT instead.

A minimum reproducible example would be useful here to understand how cdk8s is being invoked in the Lambda function.
