### ISSUE TITLE
init fails on windows (pnpm)

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [cdk8s-team/cdk8s-cli#2419]
following the tutorial
https://cdk8s.io/docs/latest/get-started/typescript/#set-up-an-environment

when I do `pnpm install -g cdk8s-cli `
`mkdir my-project`
`cd ./my-project`

I get 
` No package.json (or package.yaml, or package.json5) was found in "C:\Users\<user>\Source\repos\infrastructure-as-code".`

but if I do `pnpm init` to add a package.json then I get 
`Cannot initialize a project in a non-empty directory`

### Environment:

  - **Framework Version**: 2.198.151
  - **OS**: Windows 11
  
thanks for the help

**Comment by iliapolo** [comment]
@gabrielsantosblanchet 

>  No package.json (or package.yaml, or package.json5) was found in "C:\Users\<user>\Source\repos\infrastructure-as-code".

Which commands gives you this error?

The complete flow should be:

```console
pnpm install -g cdk8s-cli
mkdir my-project
cd ./my-project
cdk8s init typescript-app
```

Is that what you did?

**Comment by gabrielsantosblanchet** [comment]
yes that is what I did.

I don't know what happened but now it works. 

thanks
