### ISSUE TITLE
Use ts-node in typescript init templates 

### ISSUE THREAD

**Issue by danikenan** [cdk8s-team/cdk8s-cli#31]
Using ts-node for compilation and running synth will reduce clutter by removing the need for all those '*.d.ts' and '*.js'  and let user stay focus on his code. This can easily be done by change the generate `cdk8s.yml` to:
 ```
app: ts-node main.ts
```
There is no more need for compilations, nor a need for watching the files for the purpose of compilation.

On the other hand, you an add a `start`/`dev` script that will watch the `*.ts` files and generate the `yml` files on the fly. In your `package.json` add the following:
```
"scripts: {
    "start": "ts-node-dev --respawn ./main.ts",
   ...
}
```
This is much easier, cleaner and way, way faster.

**Comment by iliapolo** [comment]
Alright, let's just do this. I think the dev experience is indeed better with `ts-node`, and we should be optimizing for that.
