### ISSUE TITLE
Unable to utilize --stdout flag correctly

### ISSUE THREAD

**Issue by crazed** [cdk8s-team/cdk8s-cli#667]
When using the `cdk8s synth --stdout` command line the words "Synthesizing application" appear in STDOUT prior to the valid kubernetes manifests. This is caused by [util.ts line 43](https://github.com/cdk8s-team/cdk8s-cli/blob/2.x/src/util.ts#L43). The main issue here is when you expect the following to work:

```
cdk8s synth --stdout | kubectl apply -f -
```

What you wind up with is an errror:

```
error: error parsing STDIN: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
```

As a work around it is easy enough to do:

```
cdk8s synth --stdout | grep -v 'Synthesizing application' | kubectl apply -f -
```

However it seems easy enough to check `if stdout` and skip the `console.log` entirely. Curious what your thoughts are here, if this change is acceptable I will open a PR shortly.

**Comment by iliapolo** [comment]
Hi @crazed - makes sense to me to disable this printout when `stdout` is used. Would gladly accept a PR 👍
