### ISSUE TITLE
addDependency doesn't work with YamlOutputType.FILE_PER_RESOURCE

### ISSUE THREAD

**Issue by shinebayar-g** [cdk8s-team/cdk8s-cli#740]
By default, with `yamlOutputType: YamlOutputType.FILE_PER_CHART` k8s manifests are ordered by `addDependency` function. However this function doesn't seem to work with `yamlOutputType: YamlOutputType.FILE_PER_RESOURCE` or `FOLDER_PER_CHART_FILE_PER_RESOURCE`. It's doing nothing at the moment? According to [docs](https://cdk8s.io/docs/latest/basics/deps/#charts) charts can be ordered,
```
> cdk8s synth

dist/0000-namespace.k8s.yaml
dist/0001-application.k8s.yaml
```

but individual resources can't? I was expecting it would generate files with same numbered prefixes.

**Comment by iliapolo** [comment]
@shinebayar-g Thanks for reporting this. From looking at the code it definitely seems like this logic is missing from the `FILE_PER_RESOURCE` output type. The `FOLDER_PER_CHART_FILE_PER_RESOURCE` type should name the folders according to chart ordering - is that not what you are seeing?
