### ISSUE TITLE
Add urls from `cdk8s import <url>` to `cdk8s.yaml`

### ISSUE THREAD

**Issue by vinayak-kukreja** [cdk8s-team/cdk8s-cli#886]
### Description of the feature or enhancement:

Currently there are two ways of importing crds in cdk8s. A user can mention the url within `cdk8s.yaml` file or run `cdk8s import <url>` command. 
Executing the CLI command does not add the url to the `cdk8s.yaml`. It would be great to have the CLI import being reflected in `cdk8s.yaml` file too.

### Use Case:
This feature would help keep crds that are imported to be consistent between cdk8s.yaml and the CLI import. 

### Proposed Solution:
As part of the cdk8s CLI import code execution, the `cdk8s.yaml` file could be updated with the url for the crd passed in the import command. This url is available as `yargs` values and can be added to the yaml file.
I believe this should be the default behavior when importing crds via CLI. But if otherwise, there can be a flag added to the import command for user to opt in this feature.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@vinayak-kukreja can you also triage this issue?

**Comment by Hazzard17h** [comment]
How can I avoid this new behaviour?
Importing some CDRs from the cluster with `kubectl get crds -o json | cdk8s import /dev/stdin`, will add to the config file imports list `/dev/stdin`, that it's useless if not wrong for future imports.
