### ISSUE TITLE
Error when importing kyverno cluster policy CRD

### ISSUE THREAD

**Issue by PriestOfAdanos** [cdk8s-team/cdk8s-cli#979]
### Description of the bug:
when trying to import kyverno, errors pop up

### Reproduction Steps:
inside `ghcr.io/priestofadanos/cdk8s-docker:master` based docker container add the following to the `cdk8s.yaml`:
`- kyverno_admission:=https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno.io_admissionreports.yaml`
`- kyverno_policy:=https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno.io_clusterpolicies.yaml`

and run `cdk8s import` 

`kyverno_admission` will succed but the `kyverno_policy` will fail

### Error Log:
NOTE: Temp directory retained due to an error: /tmp/temp-Hbpacf
Error: jsii compilation failed with non-zero exit code: 1
  | [2023-05-25T14:51:12.553] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.2.32" means you should take a "devDependency" on "constructs" at "10.2.32" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdk8s" at "2.7.75" means you should take a "devDependency" on "cdk8s" at "2.7.75" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | kyverno_policy-io.kyverno.ts:339:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 339   AUDIT = "audit",
  |       ~~~~~
  | kyverno_policy-io.kyverno.ts:341:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 341   ENFORCE = "enforce",
  |       ~~~~~~~
  | kyverno_policy-io.kyverno.ts:343:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 343   AUDIT = "Audit",
  |       ~~~~~
  | kyverno_policy-io.kyverno.ts:345:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 345   ENFORCE = "Enforce",
  |       ~~~~~~~
  | kyverno_policy-io.kyverno.ts:1012:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 1012   AUDIT = "audit",
  |        ~~~~~
  | kyverno_policy-io.kyverno.ts:1014:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 1014   ENFORCE = "enforce",
  |        ~~~~~~~
  | kyverno_policy-io.kyverno.ts:1016:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 1016   AUDIT = "Audit",
  |        ~~~~~
  | kyverno_policy-io.kyverno.ts:1018:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 1018   ENFORCE = "Enforce",
  |        ~~~~~~~
  | kyverno_policy-io.kyverno.ts:7531:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 7531   AUDIT = "audit",
  |        ~~~~~
  | kyverno_policy-io.kyverno.ts:7533:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 7533   ENFORCE = "enforce",
  |        ~~~~~~~
  | kyverno_policy-io.kyverno.ts:7535:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 7535   AUDIT = "Audit",
  |        ~~~~~
  | kyverno_policy-io.kyverno.ts:7537:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 7537   ENFORCE = "Enforce",
  |        ~~~~~~~
  | kyverno_policy-io.kyverno.ts:8121:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 8121   AUDIT = "audit",
  |        ~~~~~
  | kyverno_policy-io.kyverno.ts:8123:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 8123   ENFORCE = "enforce",
  |        ~~~~~~~
  | kyverno_policy-io.kyverno.ts:8125:3 - error TS2300: Duplicate identifier 'AUDIT'.
  | 8125   AUDIT = "Audit",
  |        ~~~~~
  | kyverno_policy-io.kyverno.ts:8127:3 - error TS2300: Duplicate identifier 'ENFORCE'.
  | 8127   ENFORCE = "Enforce",
  |        ~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /usr/local/share/.config/yarn/global/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-Hbpacf
  +----------------------------------------------------------------------------------
    at newError (/usr/local/share/.config/yarn/global/node_modules/jsii-srcmak/lib/util.js:62:20)
    at ChildProcess.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/jsii-srcmak/lib/util.js:79:29)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

### Environment:

  - **cdk8s-cli version**: 2.2.32
  - **os**: Alpine Linux v3.18

---

This is :bug: Bug Report
---
Edit: 1 format
Edit 2: adding edit 1 annotation :p

**Comment by vinayak-kukreja** [comment]
Hey @PriestOfAdanos , thank you for reporting this. 

I am able to import these successfully with `version 2.41.0`. Could you confirm if it works for you with this version? 

```
❯ cdk8s import
Importing k8s v1.25.0...
Importing resources, this may take a few moments...
k8s
Importing resources, this may take a few moments...
kyverno.io
  kyverno.io/admissionreport
Importing resources, this may take a few moments...
kyverno.io
  kyverno.io/clusterpolicy
```
